sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_pull_requests: true
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS

branches:
  only:
    - master

matrix:
  include:
    - php: 7.2
      env: WP_Version=nightly
    - php: 7.1
      env: WP_VERSION=latest WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi
  - mysql --version
  - phpenv versions
  - php --version

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit --version
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi

# If the plugin has any JavaScript or CSS that should be processed,
# add the below to their respective sections so that Grunt is installed
# and all default tasks are run.
#
# To the matrix:
#
#  - php: 7.0
#    env: WP_TRAVISCI=grunt
#
# To before_script:
#
#  - npm --version
#  - node --version
#  - nvm install stable
#  - npm install -g grunt-cli
#  - npm install
#  - npm prune
#  - npm --version
#  - node --version
#
# To script:
#
#  - |
#    if [[ "$WP_TRAVISCI" == "grunt" ]] ; then
#      grunt --version
#      grunt default
#    fi
